# Generated by Django 3.0.4 on 2020-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
