# Generated by Django 3.0.4 on 2020-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(default=''),
        ),
    ]
