# Generated by Django 3.0.4 on 2020-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200404_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_4',
            field=models.TextField(default=''),
        ),
    ]
