# Generated by Django 3.0.4 on 2020-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name2',
            field=models.CharField(default='', max_length=254),
        ),
    ]
