# Generated by Django 3.0.4 on 2020-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_meal_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='description3',
            field=models.TextField(default=''),
        ),
    ]
