# Generated by Django 3.0.4 on 2020-04-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200406_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
