# Generated by Django 3.0.4 on 2020-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
