# Generated by Django 3.0.4 on 2020-05-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200512_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
